version: "3.9"
services:
  # due servizi: -> web -> redis
  web:
    container_name: ${NOME_WEB_CONTAINER}
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    container_name: ${NOME_REDIS_CONTAINER}
    image: "redis:alpine"

# Web service
# The web service uses an image that’s built from the Dockerfile in the current directory.
# It then binds the container and the host machine to the exposed port, 5000.
# This example service uses the default port for the Flask web server, 5000.
